### ISSUE TITLE
Bump traceur version?

### ISSUE THREAD

**Issue by domenic** [thlorenz/es6ify#16]
It's advancing quite rapidly these days.

**Comment by thlorenz** [comment]
Sure, we should just run the tests once and hope for the best :)

**Comment by thlorenz** [comment]
Looked into this, looks like API changed a lot.
None of [these](https://github.com/thlorenz/es6ify/blob/fc2486502b92600ec7a0e81a1dbee932d7b84aaf/compile.js#L4-L8) are there anymore.

This is gonna take a bit more than just `npm update` to get right.
I'm gonna have to look through the traceur commits to see what API I need to use now.

Don't have that kinda time on my hands this week, so PR welcome in the meantime, otherwise it'll have to wait a bit.

**Comment by domenic** [comment]
Rargh want to advertise es6ify at BrooklynJS tonight but not sure if good idea because it uses outdated traceur :-/. grunt-traceur is probably better...

**Comment by bjoerge** [comment]
I've upgraded to latest traceur in my fork over here: https://github.com/bjoerge/es6ify

Ran into a few issues and had to do a couple of workarounds to make the test suite pass, but I'll explain them better in a pull request here when I get the time (probably by the end of the week).

**Comment by thlorenz** [comment]
@bjoerge ok, looking forward to the PR. Hopefully test changes are acceptable and your changes are backwards compat.

Would love to pull something in that gets us updated to the latest traceur finally.

**Comment by thlorenz** [comment]
@domenic the hard part for es6ify is to integrate traceur API into browserify bundle/transform chain.

Is grunt-traceur a transform that works with browserify or is it just using traceur on separate file?
Does it support sourcemaps?

So fwiw you should probably consider these questions before dropping es6ify from your talk ;)

**Comment by thlorenz** [comment]
@domenic actually looked into grunt-traceur (hoping to learn how to use new traceur api).
Learnt that it actually uses an even [older traceur version](https://github.com/aaronfrost/grunt-traceur/blob/c14f38c10b34d8f81b69e1bee2e68d6d13ed6473/package.json#L35) than es6ify ;)

But nice try in egging me on :P

I'm very hopeful we'll get something working either way as I indicated above. I also want to see extra ES6 features supported in es6ify.

**Comment by dmmalam** [comment]
+1

**Comment by thlorenz** [comment]
@bjoerge I looked into the code in your fork and it looks quite good to me.
As far as I saw there was only a minor change to one test.

Would you mind doing a PR from that fork so we can discuss how to best pull it in and resolve some questions I and others may have (i.e. `modules: 'commonjs'` setting)?

Otherwise I can just cherry-pick your changes, but a PR would be preferred.
Thanks.

**Comment by bjoerge** [comment]
Cool, thanks. Will submit PR later today.

**Comment by thlorenz** [comment]
Bumped in `1.0.0`.
