### ISSUE TITLE
traceur update

### ISSUE THREAD

**Issue by bryce-larson** [thlorenz/es6ify#36]
Can you please update traceur dependency to use the latest version.  Is it possible to keep this in sync in the future?

https://github.com/google/traceur-compiler

**Comment by thlorenz** [comment]
Of course I can, whenever I have some time. 

> Is it possible to keep this in sync in the future?

If you mean automatically, then no since test have to be run and so on to check that everything still works after the upgrade.

However anyone can help by contributing via a pull request. If you feel like updating the version and running all tests to ensure nothing broke, please do so.

Please make sure that the latest traceur version has actually been published to npm as well.

**Comment by thlorenz** [comment]
traceur was updated.
