### ISSUE TITLE
turn on block bindings by default

### ISSUE THREAD

**Issue by calvinmetcalf** [thlorenz/es6ify#42]
traceur now turns let and const statements into var statements if they can be

so on http://google.github.io/traceur-compiler/demo/repl.html

``` js
const something = true;
let somethingElse = something;
if (something) {
  let a = b;
}
```

turns into 

``` js
var something = true;
var somethingElse = something;
if (something) {
  try {
    throw undefined;
  } catch (a) {
    {
      a = b;
    }
  }
}
```

**Comment by thlorenz** [comment]
Sorry, not happening, as explained, it is implemented incorrectly and still an [experimental feature](https://github.com/thlorenz/es6ify#experimental-es6-features-not-supported-by-default).
You can always turn this on for yourself, but not making this the default.

The problem is in ES5 there seems no proper way to implement this correctly. 
@domenic can tell you more.

**Comment by calvinmetcalf** [comment]
ah I thought it was just the try/catch that was the issue
