### ISSUE TITLE
Automatically add `require("traceur-runtime-path")` to every output file.

### ISSUE THREAD

**Issue by domenic** [thlorenz/es6ify#5]
This will alleviate the need for adding the runtime manually. For an example of this in action, see https://github.com/domenic/simple-jadeify.

**Comment by ForbesLindesay** [comment]
+1000

The only potential difficulty with this is modifying the source map appropriately, otherwise I'd have a pull request already :)

**Comment by ForbesLindesay** [comment]
Possibly even more awesome, make it self contained?:

``` js
var $traceurRuntime = require("traceur-runtime-path");
```

and then modify the traceur runtime by adding:

``` js
var global = {}
```

to the top and

``` js
module.exports = global.$traceurRuntime;
```

to the bottom :)

**Comment by thlorenz** [comment]
@ForbesLindesay sourcemaps shouldn't be negatively affected, since they get reevaluated during bundle creation, i.e. as long as you don't modify the bundle after it was created it should be ok.

I'm not entirely sure about the 'more awesome' idea.
Are you talking about actually changing the traceur-runtime file or wrapping it?

It sounds very useful so I'd like to incorporate it.

**Comment by ForbesLindesay** [comment]
Just wrapping it, but it turns out it's not nearly as simple as I had thought.  You'd actually have to have:

``` js
var global = {String: String, Object: Object, Array: Array};
//Original Traceur runtime unmodified here
module.exports = global.$traceurRuntime;
```

Then at the top of each es6ified file:

``` js
var $traceurRuntime = require("traceur-runtime-path");
var Deferred = $traceurRuntime.Deferred;
```

It would still modify String, Object, Array etc by adding poly-fills.  In short, it's probably not worth it.

**Comment by thlorenz** [comment]
There seems to be no nice way to do this without parsing the generated code to look for uses of `$traceurRuntime` which would be expensive.

Adding this always may lead to much larger bundles than necessary since some users may just want parts of ES6 that don't need the runtime.

So for now the best possible option is to keep adding it manually.

So closing for now, however an ingenious PR that solves this is always welcome.
